package elevator;

/**
* Generated by the ElevatorSubsystem to notify the scheduler once an Elevator has arrived.
*/
public class ElevatorEvent {
	
	private int floor;
	private int elevatorId;
	
	/**
	* Creates an instance of the ElevatorEvent class
	* @param floor The floor on which the elevator has arrived
	* @param elevatorId The elevator ID that distinguishes elevators
	*/
	public ElevatorEvent(int floor, int elevatorId) {
		this.floor = floor;
		this.elevatorId = elevatorId;
	}
	
	/**
	* Gets the floor on which the Elevator reached
	* @return floor number
	*/
	public int getFloor() {
		return floor;
	}
	
	/**
	* Gets the Elevator ID
	* @return Elevator ID number
	*/
	public int getElevatorId() {
		return elevatorId;
	}
	
	@Override
	public String toString() {
		return "Elevator " + Integer.toString(elevatorId) + " arrived at floor " + Integer.toString(floor);
		
	}
}
